void marco(int filaO, int columnaO, int largo, int ancho, char borde, char relleno);
void init_curses();
void pintar(char *name,char *name1);
void cuadritos();
void numeracion();
void dado(char *name,char *name1,int j1[2][32],int j2[2][32],int c1,int c2);
void escaleras();
void contadores(int b,int *band1,int *band2,int *cont1,int *cont2);
void giradado(int b);
void finalnumero(int b);
void monitos(int mat[2][32],int color,int i);
int process(int b,int j1[2][32],int j2[2][32],int c1,int c2,int *o1,int *o2,int band);
void llenado(int mat[31][31]);
void aristas(int mat[31][31]);
void agregarari(int p1,int p2,int mat[31][31],int peso);
void avanzarHori(int nc,int j2[2][32],int c2 ,int *o2);
int movermat(int tabla[31][31],int *o1,int *o2,int band,int b,int j1[2][32],int j2[2][32]);
void ganador(int o1,int o2,int band,char *name,char *name1);
void subesc(int p,int j1[2][32],int *o1,int *o2,int band,int j2[2][32]);
void bajser(int p,int j1[2][32],int *o1,int *o2,int band,int j2[2][32]);
